translations = {
    'pt': {
        'greeting': 'Olá! Escolha uma opção:',
        'enter_amount': '💰 Digite o valor',
        'change_language': '🌍 Trocar Idioma',
        'send_image': '📷 Enviar Imagem',
        'exit': '❌ Encerrar',
        'groceries': '🛒 Supermercado',
        'transport': '⛽ Gasolina/Transporte',
        'leisure': '🎮 Lazer',
        'food': '🍽️ Alimentação',
        'bills': '💡 Contas',
        'health': '🏥 Saúde',
        'others': '📦 Diversos',
        'register_again': '🔄 Registrar Novamente',
        'back_to_main': '🏠 Menu Principal',
        'language_prompt': 'Escolha seu idioma:',
        'language_set': 'Idioma alterado com sucesso!',
        'amount_prompt': '✅ Valor aceito! Escolha a categoria:',
        'invalid_amount': '❌ Formato inválido! Use números (ex: 50 ou 25,99)',
        'saved_expense': '💾 Salvo: R${amount} em {category}',
        'db_error': '🔥 Erro ao salvar no banco de dados!',
        'send_image': '📷 Enviar Imagem',
        'image_prompt': '📤 Envie agora a imagem da despesa:',
        'image_success': '✅ Imagem recebida!',
        'image_error': '❌ Isso não parece ser uma imagem válida.',
        'db_error': '⚠️ Ocorreu um erro interno. Tente novamente mais tarde.',
        'saved_expense': '✅ Salvo: R${amount} em {category}',
        'settings': '⚙️ Configurações',
        'invalid_format': '❌ Formato inválido! Use: VALOR [DESCRIÇÃO]\nEx: 958.80 Almoço ou 100,50',
        'ask_amount': '💵 *Digite o valor da despesa:*\nEx: 50.99',
        'ask_description': '📝 *Adicione uma descrição (opcional):*',
        'skip_description': '⏭ Pular descrição',
        'select_category': '🗂️ Selecione a categoria da despesa:',
        'saved_expense': 'Despesa registrada com sucesso!',
        'auto_category': '🦾 Reconhecimento Automático',
        'add_card': '💳 Cadastrar Cartão',
        'enter_card_details': '🔢 *Digite os 4 últimos dígitos do cartão:*\nEx: 4321 ou 4321 Nubank',
        'card_added': '✅ Cartão cadastrado com sucesso!',
        'invalid_card_format': '❌ Formato inválido! Use 4 dígitos + apelido opcional',
        'card_error': '⚠️ Erro ao cadastrar cartão',
        'my_cards': '💳 Meus Cartões',
        'your_cards': '📇 Seus Cartões Cadastrados:',
        'no_cards': 'Você não tem cartões cadastrados.',
        'card_item': '• {nickname} (···{last_four})',
        'wrong_flow': '⚠️ Conclua o cadastro do cartão primeiro!',
        'card_success': "✅ Cartão cadastrado!",
        'back_to_settings': "⚙️ Voltar às configurações",
        'select_payment_method': '💸 *Como você pagou?*',
        'saved_expense': '✅ **Gasto salvo!**\n\nValor: R$ {amount}\nCategoria: {category}\nMétodo: {payment_method}',        
        'enter_card_details': (
            "💳 *Como cadastrar seu cartão:*\n"
            "1. Digite os **4 últimos dígitos** do cartão\n"
            "2. (Opcional) Adicione um apelido\n\n"
            "Exemplo: `4321 Nubank` ou apenas `4321`"
        ),
    },
    'en': {
        'greeting': 'Hello! Choose an option:',
        'enter_amount': '💰 Enter amount',
        'change_language': '🌍 Change Language',
        'send_image': '📷 Send Image',
        'exit': '❌ Exit',
        'groceries': '🛒 Groceries',
        'transport': '⛽ Transport',
        'leisure': '🎮 Leisure',
        'food': '🍽️ Food',
        'bills': '💡 Bills',
        'health': '🏥 Health',
        'others': '📦 Others',
        'register_again': '🔄 Register Again',
        'back_to_main': '🏠 Main Menu',
        'language_prompt': 'Choose your language:',
        'language_set': 'Language changed successfully!',
        'amount_prompt': '✅ Amount accepted! Choose a category:',
        'invalid_amount': '❌ Invalid format! Use numbers (ex: 50 or 25.99)',
        'saved_expense': '💾 Saved: ${amount} in {category}',
        'db_error': '🔥 Failed to save to database!',
        'send_image': '📷 Send Image',
        'image_prompt': '📤 Now send the expense image:',
        'image_success': '✅ Image received!',
        'image_error': '❌ This doesn\'t look like a valid image.',
        'db_error': '⚠️ An internal error occurred. Please try again later.',
        'saved_expense': '✅ Saved: ${amount} in {category}',
        'settings': '⚙️ Settings',
        'invalid_format': '❌ Invalid format! Use: AMOUNT [DESCRIPTION]\nEx: 958.80 Lunch or 100.50',
        'ask_amount': '💵 *Enter the expense amount:*\nEx: 50.99',
        'ask_description': '📝 *Add a description (optional):*',
        'skip_description': '⏭ Skip description',
        'select_category': '🗂️ Select expense category:',
        'saved_expense': 'Expense saved successfully!',
        'auto_category': '🦾 Auto Recognition',
        'add_card': '💳 Add Credit Card',
        'enter_card_details': '🔢 *Enter last 4 digits:*\nEx: 4321 or 4321 Nubank',
        'card_added': '✅ Card registered successfully!',
        'invalid_card_format': '❌ Invalid format! Use 4 digits + optional nickname',
        'card_error': '⚠️ Error saving card',
        'my_cards': '💳 My Cards',
        'your_cards': '📇 Your Registered Cards:',
        'no_cards': 'You have no registered cards.',
        'card_item': '• {nickname} (···{last_four})',
        'wrong_flow': '⚠️ Complete the card registration first!',
        'card_success': "✅ Card registered!",
        'back_to_settings': "⚙️ Back to settings",
        'select_payment_method': '💸 *How did you pay?*',
        'saved_expense': '✅ **Expense saved!**\n\nAmount: ${amount}\nCategory: {category}\nMethod: {payment_method}',
        'enter_card_details': (
            "💳 *How to register your card:*\n"
            "1. Enter the **last 4 digits**\n"
            "2. (Optional) Add a nickname\n\n"
            "Example: `4321 Nubank` or just `4321`"
        ),
    }
}