translations = {
    'pt': {
        'greeting': 'Olá! Escolha uma opção:',
        'enter_amount': '💰 Digite o valor',
        'change_language': '🌍 Trocar Idioma',
        'send_image': '📷 Enviar Imagem',
        'exit': '❌ Encerrar',
        'groceries': '🛒 Supermercado',
        'transport': '⛽ Gasolina/Transporte',
        'leisure': '🎮 Lazer',
        'food': '🍽️ Alimentação',
        'bills': '💡 Contas',
        'health': '🏥 Saúde',
        'others': '📦 Diversos',
        'register_again': '🔄 Registrar Novamente',
        'back_to_main': '🏠 Menu Principal',
        'language_prompt': 'Escolha seu idioma:',
        'language_set': 'Idioma alterado com sucesso!',
        'amount_prompt': '✅ Valor aceito! Escolha a categoria:',
        'invalid_amount': '❌ Formato inválido! Use números (ex: 50 ou 25,99)',
        'saved_expense': '💾 Salvo: R${amount} em {category}',
        'db_error': '🔥 Erro ao salvar no banco de dados!',
        'send_image': '📷 Enviar Imagem',
        'image_prompt': '📤 Envie agora a imagem da despesa:',
        'image_success': '✅ Imagem recebida!',
        'image_error': '❌ Isso não parece ser uma imagem válida.',
        'db_error': '⚠️ Ocorreu um erro interno. Tente novamente mais tarde.',
        'saved_expense': '✅ Salvo: R${amount} em {category}',
        'auto_category': '🦾 Reconhecimento Automático'
    },
    'en': {
        'greeting': 'Hello! Choose an option:',
        'enter_amount': '💰 Enter amount',
        'change_language': '🌍 Change Language',
        'send_image': '📷 Send Image',
        'exit': '❌ Exit',
        'groceries': '🛒 Groceries',
        'transport': '⛽ Transport',
        'leisure': '🎮 Leisure',
        'food': '🍽️ Food',
        'bills': '💡 Bills',
        'health': '🏥 Health',
        'others': '📦 Others',
        'register_again': '🔄 Register Again',
        'back_to_main': '🏠 Main Menu',
        'language_prompt': 'Choose your language:',
        'language_set': 'Language changed successfully!',
        'amount_prompt': '✅ Amount accepted! Choose a category:',
        'invalid_amount': '❌ Invalid format! Use numbers (ex: 50 or 25.99)',
        'saved_expense': '💾 Saved: ${amount} in {category}',
        'db_error': '🔥 Failed to save to database!',
        'send_image': '📷 Send Image',
        'image_prompt': '📤 Now send the expense image:',
        'image_success': '✅ Image received!',
        'image_error': '❌ This doesn\'t look like a valid image.',
        'db_error': '⚠️ An internal error occurred. Please try again later.',
        'saved_expense': '✅ Saved: ${amount} in {category}',
        'auto_category': '🦾 Auto Recognition'
    }
}